[FEAT] 엔티티 수정
hufs-sports-live/server pull request #35
Opened 2023-11-01 07:48 UTC by Jin409

## 🌍 이슈 번호
- closed #34 

## 📝 구현 내용
- erd 수정에 따른 엔티티 전체 수정
- 엔티티 수정에 따른 dto 및 service 코드 수정

2023-11-01 10:59 UTC, ldk980130 requested changes
안녕하세요! 빠르게 엔티티 수정해주셨네요. 첫 리뷰 드리는 거라 떨리지만 잘 부탁드립니다
ㅎㅎ  

제가 놓친 부분이 있을 수도 있지만 최대한 변경된 파일 중심으로 리뷰 드렸습니다! 좀 더 상세한 리뷰는 도메인에 대한 이해가 좀 더 진행되어야 할 수 있을 것 같지만 제가 이해한 도메인을 바탕으로 피드백이나 질문 남겼습니다. 한 번 같이 얘기 나눠보면 좋을 것 같아요!

2023-11-01 10:59 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/domain/Comment.java
> +
이 댓글이 블락 됐는지 물어보는 메서드인 것 같아요! getter로써 취급하기 보단 `isBlocked()`라는 이름을 붙이면 어떨까요?

2023-11-01 10:59 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/domain/Report.java
> +
신고 객체를 `comment` 패키지 내부에 위치시킨 이유가 있을까요? 👀

2023-11-01 10:59 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java
> +                .game(team.getGame())
### Builder 사용에 대해
거의 모든 도메인 엔티티에 Builder를 사용하고 따로 생성자를 사용한 생성은 하지 않고 있더라구요. 이유가 있을까요? Builder가 코드를 깔끔하게 만들어주기는 하지만 개인적으로 저는 다음의 이유 때문에 잘 사용하지는 않아요.
1. 필요한 값이 누락될 위험이 있다. 
2. 컴파일 타임에 누락된 값을 잡아주지 못한다.
3. 생성자나 정적 팩터리 메서드를 사용하면 객체 생성에 비즈니스 로직을 담을 수 있다.

예를 들어 `Comment`의 경우 처음 생성하게 되면 당연히 `isBlocked`가 `false`입니다. 그런데 빌더만 사용하게 되면 생성할 때마다 flase로 넣어줘야 겠죠. createdAt도 마찬가지에요. 아래 두 도메인 규칙에 따라 생성자를 만들면 더 의미가 명확하고 값을 누락시킬 일도 없을거라 생각해요
- `Comment`는 생성될 때 지금 시간으로 생성
- `Comment`는 생성될 때 기본적으로 블락되지 않음
``` java
    public Comment(String content, GameTeam gameTeam, Game game) {
        this.content = content;
        this.gameTeam = gameTeam;
        this.game = game;
        this.isBlocked = false;
        this.createdAt = LocalDateTime.now();
    }
```

이에 대해선 어떻게 생각하시나요?

2023-11-01 10:59 UTC, ldk980130 commented on src/main/java/com/sports/server/common/ValidatorMessages.java
>  }
`ValidatorMessage`가 `common` 패키지에 위치하고 있어요. 모든 도메인에 대한 검증 메시지를 여기서 다 관리한다고 보면 될까요?

`common`은 다른 패키지들에서 공통적으로 쓰이는 부분들을 정의하는 곳이라고 했을 때 이런 특정 도메인에 국한된 메시지를 관리하는 것은 나중에 서비스가 커졌을 때 복잡해질 거라 생각하는데 어떻게 생각하시나요?

2023-11-01 10:59 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/domain/Comment.java
> +import lombok.NoArgsConstructor;
`Comment` 기본생성자 접근제어자가 `public`이던데 `protected`로 좁혀주세요!

2023-11-01 10:59 UTC, ldk980130 commented on src/main/java/com/sports/server/game/domain/Game.java
> +    private Sports sports;
DB 테이블명은 `sports`로 쓰더라도 자바 안에서는 `Sport`로 단수 취급하면 어떨까요? `Sprots`면 일급 컬렉션처럼 보여서 헷갈릴 수도 잇을 것 같아요

2023-11-01 10:59 UTC, ldk980130 commented on src/main/java/com/sports/server/game/presentation/GameController.java
>      private final CommentService commentService;
``` java
    @GetMapping("/{gameId}/comments")
    public ResponseEntity<List<CommentResponseDto>> getAllComments(@PathVariable final Long gameId) {
        return ResponseEntity.ok(commentService.getAllCommentsWithGameId(gameId));
    }
```
위 댓글 조회 API 때문에 `GameController`에서 `CommentService` 의존하고 있네요. 그런데 `Comment` 객체에서는 `GameTeam` 엔티티와 `Game` 엔티티를 단방향 의존하고 있어요. 이렇게 되면 패키지 간 순환참조가 발생하게 되고 이는 장기적으로 봤을 때 순환참조로 인한 문제가 발생할 수도 있어요.

객체 간 참조도 단방향으로 하는 것이 좋고 패키지 간 참조도 단방향으로 흐르게 하는 것이 좋아요. 댓글 조회 API는 `CommentContrller`로 옮기면 어떨까요? `comment` 패키지에선 원래 `game`쪽을 참조하고 있기에 문제 없을 것 같아요.

2023-11-01 15:41 UTC, Jin409 commented on src/main/java/com/sports/server/comment/domain/Comment.java
> +
네! 그렇게 수정하도록 하겠습니당
꼭 필요하지 않은 경우에는 getter 는 지양하는 버릇을 들여야겠어요

2023-11-01 15:43 UTC, Jin409 commented on src/main/java/com/sports/server/comment/domain/Report.java
> +
댓글에 대한 신고 기능만 현재 고려하고 있기 때문에 comment 패키지 내부에 위치 시켰어요!
혹시 더 나은 방안이 있다고 생각되시면 알려주세요!

2023-11-01 15:47 UTC, Jin409 commented on src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java
> +                .game(team.getGame())
저는 단순히 가독성 측면에서 Builder 를 습관처럼 써왔던 것 같아요!
객체 밖에서 객체를 생성할 때 생성자로 생성하게 되면 필드가 많은 경우에는 어떤 필드에, 어떤 값이 담기는지 명확히 보이지 않아서 써왔어요.

동규님이 말씀해주신 부분에 동의합니다! 
Builder 가 누락된 필드를 실제로 잡아주지 못해서 제가 실수한 경우도 더러 있었어서.. 이참에 리팩토링 해볼게요!

이건 개인적인 궁금증인데.. 말씀하신 3번 `생성자나 정적 팩터리 메서드를 사용하면 객체 생성에 비즈니스 로직을 담을 수 있다.` 의 경우, 객체가 생성될 때 유효성 검사도 동시에 이루어지는 것 역시 3번에 해당된다고 볼 수 있을까요?

2023-11-01 15:53 UTC, Jin409 commented on src/main/java/com/sports/server/common/ValidatorMessages.java
>  }
제가 common 에 위치시켰던 이유는, 도메인에 해당하지 않는 dto 에도 해당 메시지가 쓰일 수 있다고 생각했기 때문인데요..

예를 들어서 comment 패키지에 위치한 CommentRequestDto 에도 TEAM_ID_CANNOT_BE_BLANK 가 쓰이기 때문에 common 에 위치하는게 맞겠다고 생각했었어요!

흠.. 그대로 common 에 위치시키고 enum 으로 관리한다면 어떨까요? 
제가 당장 떠오르는 해결책은 enum 으로 그룹화하는 것 밖에 없는데 혹시 떠오르는 다른 해결책이 있으실까요? 👀

2023-11-01 15:53 UTC, Jin409 commented on src/main/java/com/sports/server/comment/domain/Comment.java
> +import lombok.NoArgsConstructor;
헉 넹! 확인입니다

2023-11-01 15:54 UTC, Jin409 commented on src/main/java/com/sports/server/game/domain/Game.java
> +    private Sports sports;
좋아요! 동의합니다.

2023-11-02 07:41 UTC, ldk980130 approved these changes
고쳐주신거 확인했습니다! 추가로 생각해볼만한 점이나 의견 남겨두었어요. 

한 번 생각해보시고 수정하셔도 되고 당장은 안하셔도 상관 없을 것 같아 approve 남깁니다. 수고하셨습니다!!

2023-11-02 07:41 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/domain/Comment.java
> +    }
👍

2023-11-02 07:41 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/domain/Report.java
> +
나중에 신고에 대한 별도의 `controller`, `service`가 출현할텐데 `comment` 패키지 내부에 있는게 어색하다고 생각했어요! `report`라는 별도의 패키지안에 정의하는건 어떨까요? 기능이 확장해 감에 따라 `comment` 패키지 안에 담기엔 넘칠 것도 같네요

2023-11-02 07:41 UTC, ldk980130 commented on src/main/java/com/sports/server/common/ValidatorMessages.java
>  }
### 의존성에 대해
보통 'A가 B를 의존한다'고 하면 'B의 변경에 A가 영향을 받는다'입니다. 

다른 도메인 패키지에서 `common` 패키지를 의존하니 `common` 패키지의 변경에 영향을 받겠죠. 그래서 `common` 패키지를 수정할 때 다른 패키지들에 갈 영향을 고려하여 설계를 하게 됩니다. 하지만 다른 패키지에서는 `common` 패키지를 신경쓰면서 자신을 수정할 필요는 없습니다. 이것이 단방향 의존의 장점이기도 합니다. 
(`common` 패키지를 수정하는 개발자는 다른 도메인을 개발하는 개발자 눈치를 봐야하지만 다른 도메인을 개발하는 개발자는 `common` 눈치를 안봐도 되죠.)

하지만 각 도메인에 쓰일 검증 메시지가 `common`에 위치하게 되면 논리적인 의존이 생기게 됩니다. 만약 도메인 개발을 하는 개발자가 검증에 관해 수정해야 한다면 `common` 패키지의 검증 메시지도 고쳐야 합니다. 결국 서로서로 변경을 전파하는 문제가 발생하게 되는 것이죠.

### 함께 변하는 것은 같이
어떤 클래스들을 한 패키지에 묶을까를 고민할 때 '함께 변하는 것'을 같이 묶고는 합니다. 그렇기에 같은 책임을 공유하는 도메인들을 한데 묶곤 하는 것이죠. 검증 메시지는 특정 도메인의 변경에 영향을 심하게 받고 함께 변합니다. 같이 변하는 것을 함께 둔다는 취지에선 각 검증 메시지들을 각 패키지 안으로 옮기는 게 좋다고 생각해요.

댓글에 관한 기능을 고치게 된다면 `comment` 패키지 내부에만 file change가 발생하는 것이 좋지 않을까요? `common` 패키지 내에 file change 없이 말이죠

2023-11-02 15:23 UTC, Jin409 commented on src/main/java/com/sports/server/comment/domain/Report.java
> +
좋아요! 패키지가 너무 많아지려나 싶어서 그나마 연관성이 짙은 comment 내부에 위치시켜야겠다고 생각했는데 다시 생각해보니 신고 로직과 댓글 관련 로직이 완전히 상이하겠네요. 피드백 감사합니닷!

2023-11-02 15:35 UTC, Jin409 commented on src/main/java/com/sports/server/common/ValidatorMessages.java
>  }
그렇겠네요.. 이 부분은 제가 좀 더 고민해보고 수정해보려고 할게요!
제가 헷갈리는 이유가 위에서 예시로 든 CommentRequestDto 에서도 comment 와는 전혀 상관이 없는 TEAM_ID_CANNOT_BE_BLANK 가 쓰이기 때문인 것 같아요.
이런 경우에는 어떻게 해야 할까요? 도메인 별로 분리를 하고, 중복이 되더라도 어느 정도 감안해야 하는 부분이려나요? 
동규님은 어떻게 생각하시는지 궁금합니당.

2023-11-02 15:37 UTC, merged

2023-11-02 15:47 UTC, ldk980130 commented on src/main/java/com/sports/server/common/ValidatorMessages.java
>  }
문구의 내용이랑은 크게 상관이 없는 것 같아요. 이 메시지는 어떤 기능 변경에 가장 큰 영향을 받을까요? 팀 기능이 변경되면 이 문구도 변경될까요? 댓글 변경에 큰 영향을 받을까요? 가장 큰 영향을 받는건 `CommentRequestDto` 내부에서 쓰이기에 댓글 관련 API 변경에 영향을 받을 가능성이 커 보여요. 결국 중요한건 '댓글을 생성하는데 팀이 필요하다'라는 것이니까요.

팀 ID가 필요할 수도 있어서 `GameTeam` 패키지 내에서도 이 검증 문구가 필요할 수도 있겠죠. 이에 대해선 '우발적 중복'이라는 키워드로 한 번 구글링해보셔도 좋을 것 같아요~

>우발적 중복
서로 같아보이는 코드가 서로 다른 속도와 이유로 변경된다면 그 코드들은 중복이 아니다.
진짜 중복과 우발적 중복을 신중하게 구분해야 하고,
함부로 중복을 통합하지 말아야 한다.

2023-11-02 15:48 UTC, Jin409 commented on src/main/java/com/sports/server/common/ValidatorMessages.java
>  }
코오오 좋은 답변 감사합니다! 해당 부분 리팩토링도 진행해볼게욧 🫡