[FEAT] 응원하기 개수 확인 기능 구현
hufs-sports-live/server pull request #45
Opened 2023-11-10 07:01 UTC by Jin409

## 🌍 이슈 번호
- closed #44 

## 📝 구현 내용
- 경기의 아이디를 통해 경기에 참여하는 팀 전체를 찾는 메서드 repository에 추가 
- 경기의 아이디를 통해 응원 개수를 조회하는 기능 구현

## 🍀 확인해야 할 부분
- GameTeamService 를 따로 분리해야 했을까요? 분리할 정도의 사이즈가 아니라고 생각하기도 하고,, GameTeam 자체가 game 에 너무 종속적이라 어차피 경기 조회를 계속해서 해야 할 것 같아서 GameService 내부에 뒀는데 동규님의 의견은 어떠신지 궁금합니다 !

2023-11-10 12:02 UTC, ldk980130 requested changes
간단한 기능이라 빠르게 구현해주셨군요! 일단 코멘트 남긴 부분은 간단히 생각해볼 점만 남겨놨습니다.

### DTO 중복에 대해
상속을 통해 중복되는 코드를 제거하면 전체적인 코드 양이 줄어드는 것은 사실입니다만 무조건 중복을 없애는 게 좋은가에 대해선 생각해볼 점이 있어요. 특히 DTO에는 말이죠. response DTO는 결국 API 스펙입니다. 서로 다른 API가 당장 비슷해보여 중복되는 코드를 작성했지만 만약 한 API가 나중에 독립적으로 변화한다면 어떻게 될까요?

https://techblog.woowahan.com/2647/
위 기술 블로그에 이런 내용이 나와요. (블로그를 다 읽을 필요는 없습니다..ㅎ)
```
<클린 아키텍처> 책에서 이에 대한 좋은 내용을 언급하는데, 그 내용은 중복에도 종류가 있다는 것이다.

- 진짜 중복
  - 한 인스턴스가 변경되면, 동일한 변경을 그 인스턴스의 모든 복사본에 반드시 적용해야한다.

- 우발적 중복(거짓된 중복)
  - 중복으로 보이는 두 코드의 영역이 각자의 경로로 발전한다면, 즉 서로 다른 속도와 다른 이유로 변경된다면 이 두 코드는 진짜 중복이 아니다.

저는 저장과 수정 사이의 DTO의 중복은 우발적 중복에 속한다고 생각합니다. 초반에는 코드가 비슷할지 모르지만 각 기능은 서로 다른 이유와 속도로 변경될 가능성이 높기 때문입니다.
```
위 내용을 토대로 생각했을 때 중복처럼 보이는 API여도 다르게 발전할 가능성이 존재한다면 중복이더라도 별도로 나두는게 좋은 것 같아요. A API에 대한 기능 변경을 구현하는데 상속으로 묶여있어서 B API도 같이 건드려야 하면 불필요한 변경이 전파되기 때문이에요.

그럼에도 아 이 중복 API들은 죽었다 깨어나도 변하지 않고 같이 갈 것 같다면 중복을 없애도 될 것 같아요. 승희님은 어떻게 보시나요?

### GameTeamService가 필요할지?
저도 생각해 봤는데 당장은 GameService 안에서 처리해도 될 것 같아요.
- `Game`이 `GameTeam`과 `GameTeamPlayer`를 관리하는 루트 도메인 역할
- `GameTeam`이 확장되면 새로운 루트로 독립할 수도 있지만 아직은 괜찮은 것 같음
- 한 `GameTeam`의 응원을 조회하는 것이 아닌 `Game`의 모든 응원을 조회하기에 아직 적절한 배치라고 생각됨

사실 조회 로직은 아예 별도의 클래스 더 나아가면 패키지에 두는 걸 더 선호하기는 하는데 당장은 이렇게 해도 괜찮을 것 같습니다.

### 동시성은 어떻게?
다만 현재 아직 응원하기에 대한 동시성을 어떻게 처리할지 확정이 나지 않은 상태에요. 비관적 락을 사용하게 되면 이 로직으로도 문제 없지만 레디스 혹은 이벤트 소싱을 사용하게 되면 조회 로직이 좀 달라져야 하네요. 이번에 코드리뷰하면서 결정해 보는걸로 해요!

2023-11-12 07:50 UTC, Jin409 commented on src/main/java/com/sports/server/game/application/GameService.java
> +        List<GameTeam> gameTeams = gameTeamRepository.findAllByGame(game);
존재하지 않는 경기에 대해 요청이 온 경우에 404를 던져야 한다고 생각해서 그렇게 했어요!
만약 gameTeamRepository.findByGameId(gameId) 로 존재하지 않는 경기 id 로 조회하면 200 이 떨어지니까 한번 더 조회하는 게 좋을 것 같다고 생각했는데 어떻게 생각하시는지 궁금하네요!

2023-11-12 07:51 UTC, Jin409 commented on src/main/java/com/sports/server/game/application/GameService.java
> +        return gameTeams.stream().map(GameTeamCheerResponseDto::new).toList();
좋아요! 저도 그 편이 훨씬 가독성이 좋을 것 같습니당 수정할게요!

2023-11-12 08:08 UTC, Jin409 commented
> 간단한 기능이라 빠르게 구현해주셨군요! 일단 코멘트 남긴 부분은 간단히 생각해볼 점만 남겨놨습니다.
> 
> ### DTO 중복에 대해
> 상속을 통해 중복되는 코드를 제거하면 전체적인 코드 양이 줄어드는 것은 사실입니다만 무조건 중복을 없애는 게 좋은가에 대해선 생각해볼 점이 있어요. 특히 DTO에는 말이죠. response DTO는 결국 API 스펙입니다. 서로 다른 API가 당장 비슷해보여 중복되는 코드를 작성했지만 만약 한 API가 나중에 독립적으로 변화한다면 어떻게 될까요?
> 
> https://techblog.woowahan.com/2647/ 위 기술 블로그에 이런 내용이 나와요. (블로그를 다 읽을 필요는 없습니다..ㅎ)
> 
> ```
> <클린 아키텍처> 책에서 이에 대한 좋은 내용을 언급하는데, 그 내용은 중복에도 종류가 있다는 것이다.
> 
> - 진짜 중복
>   - 한 인스턴스가 변경되면, 동일한 변경을 그 인스턴스의 모든 복사본에 반드시 적용해야한다.
> 
> - 우발적 중복(거짓된 중복)
>   - 중복으로 보이는 두 코드의 영역이 각자의 경로로 발전한다면, 즉 서로 다른 속도와 다른 이유로 변경된다면 이 두 코드는 진짜 중복이 아니다.
> 
> 저는 저장과 수정 사이의 DTO의 중복은 우발적 중복에 속한다고 생각합니다. 초반에는 코드가 비슷할지 모르지만 각 기능은 서로 다른 이유와 속도로 변경될 가능성이 높기 때문입니다.
> ```
> 
> 위 내용을 토대로 생각했을 때 중복처럼 보이는 API여도 다르게 발전할 가능성이 존재한다면 중복이더라도 별도로 나두는게 좋은 것 같아요. A API에 대한 기능 변경을 구현하는데 상속으로 묶여있어서 B API도 같이 건드려야 하면 불필요한 변경이 전파되기 때문이에요.
> 
> 그럼에도 아 이 중복 API들은 죽었다 깨어나도 변하지 않고 같이 갈 것 같다면 중복을 없애도 될 것 같아요. 승희님은 어떻게 보시나요?
> 
> ### GameTeamService가 필요할지?
> 저도 생각해 봤는데 당장은 `GameService` 안에서 처리해도 될 것 같아요.
> 
> * `Game`이 `GameTeam`과 `GameTeamPlayer`를 관리하는 루트 도메인 역할
> * `GameTeam`이 확장되면 새로운 루트로 독립할 수도 있지만 아직은 괜찮은 것 같음
> * 한 `GameTeam`의 응원을 조회하는 것이 아닌 `Game`의 모든 응원을 조회하기에 아직 적절한 배치라고 생각됨
> 
> 사실 조회 로직은 아예 별도의 클래스 더 나아가면 패키지에 두는 걸 더 선호하기는 하는데 당장은 이렇게 해도 괜찮을 것 같습니다.
> 
> ### 동시성은 어떻게?
> 다만 현재 아직 응원하기에 대한 동시성을 어떻게 처리할지 확정이 나지 않은 상태에요. 비관적 락을 사용하게 되면 이 로직으로도 문제 없지만 레디스 혹은 이벤트 소싱을 사용하게 되면 조회 로직이 좀 달라져야 하네요. 이번에 코드리뷰하면서 결정해 보는걸로 해요!

# DTO 중복에 대해

저번에 이야기했던 우발적 중복이 여기에도 나오는군요..! 
단순히 보여지는 화면에 의존하는 dto 가 변경을 전파하게 된다면 확실히 좋은 구조가 아닐 것 같네요. 좋은 의견 감사합니다!

2023-11-12 08:11 UTC, ldk980130 commented on src/main/java/com/sports/server/game/application/GameService.java
> +        List<GameTeam> gameTeams = gameTeamRepository.findAllByGame(game);
아 그런 이유가 있었군요. 그러면 이 코드로도 괜찮은 것 같습니다! 게임 하나 조회하는건 그렇게 성능이 나쁜 것도 아니니까요.

2023-11-12 08:25 UTC, ldk980130 approved these changes
👍

2023-11-12 08:29 UTC, merged