Feature/#47 cheer post
hufs-sports-live/server pull request #49
Opened 2023-11-12 09:36 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분

2023-11-13 07:54 UTC, ldk980130 requested changes
응원하기 기능 수고하셨습니다!

Game 관련하여 controller, service 분리와 병합에 대해서는 승희님 의견에 동의합니다! 프레젠 레이어에선 합치고 application 레이어에선 분리하는 거 좋은 것 같아요 👍 

나머지 내용에 관해서는 모두 코멘트에 달아 놓았습니다. 확인해주세요!

2023-11-13 07:54 UTC, ldk980130 commented on src/main/java/com/sports/server/game/application/GameTeamService.java
> +    }
이 메서드도 `GameServiceUtil`에 넣어서 `엔티티가 존재하는지 검사`하는 클래스로 만드는 건 어떨까요? (`EntityUtils.validateIfExists(...)`)

`EntityManager`의 아래 기능을 사용해서 제네릭으로 추상화할 수 있을 것도 같네요! 에러 메세지까지 공통적으로 처리할 수 있을진 모르겠지만 한 번 고민하는 것도 재밌을 것 같아요!
``` java
Game game = em.find(Game.class, gameId);
if (game == null) {
    //...
}
```

2023-11-13 07:54 UTC, ldk980130 commented on src/main/java/com/sports/server/game/application/GameTeamService.java
> +        getGameTeamWithId(cheerRequestDto.gameTeamId());
`getGameTeamWithId`의 경우 반환값이 어디에도 쓰이지 않고 있더라구요. 훗날 쓰일 수도 있어서 반환값을 만들어 놓은 것일까요? 아니면 반환값이 없는 메서드와 있는 메서드를 필요에 따라 호출하는 방법도 있을 것 같아요!

2023-11-13 07:54 UTC, ldk980130 commented on src/main/java/com/sports/server/game/domain/GameTeamRepository.java
> +    void updateCheerCount(@Param("gameTeamId") Long gameTeamId, @Param("cheerCount") int cheerCount);
`Modifying`의 경우 영속성 컨텍스트를 무시하고 쿼리를 날리기 때문에 영속성 컨텍스트에 있는 변경이 반영되지 않는 엔티티 때문에 문제가 있을까봐 걱정해주신 것 같아요 맞을까요?

그런데 수정 쿼리 이후 다시 엔티티를 조회할 일도 없고 해서 필요없을 것 같긴 합니다. 테스트에서도 한 트랜잭션에서 테스트를 하는 것이 아닌 분리된 트랜잭션에서 테스트 수행, 테스트 검증이 이루어지기에 영속성 컨텍스트가 남아있는 걸로 인한 문제는 없을 것 같아요. 테스트를 해서 잘 돌아갔다면 문제 없을 것 같습니다 👍

2023-11-13 07:54 UTC, ldk980130 commented on src/main/java/com/sports/server/game/presentation/GameController.java
> +        return ResponseEntity.ok(null);
`ResponseEntity.ok().build()`를 사용하면 null을 굳이 넣지 않아도 됩니다.

2023-11-13 07:54 UTC, ldk980130 commented on src/test/java/com/sports/server/game/acceptance/GameTeamAcceptanceTest.java
> +                .isEqualTo(cheerCountBeforePost + 1);
테스트 잘 작성해주신 것 같습니다! 

저는 개인적으로 이렇게 E2E 테스트의 경우에는 api 스펙인 dto 제외하곤 거의 프로덕션 코드를 사용하지 않고 api로만 접근해서 테스트를 하는 편입니다. (black box test)

실제로 E2E 테스트만 작성해도 웬만한 운영 환경에서의 버그를 사전에 방지할 수 있어요. 시간이 있으면 도메인, 서비스 테스트 등의 단위 테스트도 수행하는게 좋지만요.

서비스 테스트 한 번 작성해 보는 것은 어떨까요? 그리고 아무래도 동시성이 염려되는 테스트다 보니 정말 '여러 스레드에서 접근해도 안전한지' 테스트해보는 것도 재밌을 것 같네요 😄 (동시성 테스트는 어떻게?)

2023-11-13 07:54 UTC, ldk980130 commented on src/test/resources/game-fixture.sql
> +
저보다 픽스처 작성을 더 친절하게 해주신 것 같네요 👍 저도 sql 파일을 좀 더 가독성 있게 작성해보도록 하겠습니다!

2023-11-13 07:54 UTC, ldk980130 commented on src/test/resources/game-fixture.sql
> +SET foreign_key_checks = 0;
모든 엔티티를 연관관계에 따라 다 작성해줄 수 없기 때문에 외래키 제약을 풀고 픽스처를 넣는 방법을 선택했었는데요.

픽스처 세팅이 끝나면 다시 외래키 설정을 1로 켜주세요! 테스트를 수행하는 시점에선 외래키 참조 제약이 잘 동작해야 버그를 잘 잡을 수 있을 것 같습니다.

2023-11-14 12:02 UTC, Jin409 commented on src/main/java/com/sports/server/game/application/GameTeamService.java
> +    }
추후에 리팩토링합씨다..

2023-11-14 12:03 UTC, Jin409 commented on src/main/java/com/sports/server/game/application/GameTeamService.java
> +        getGameTeamWithId(cheerRequestDto.gameTeamId());
훗날 쓰일 수도 있어서 만들어뒀는데 이 부분도 리팩토링하면 반환값 없는 메서드를 호출하는 방식으로 해결할 수 있겠네요!

2023-11-14 12:05 UTC, Jin409 commented on src/main/java/com/sports/server/game/domain/GameTeamRepository.java
> +    void updateCheerCount(@Param("gameTeamId") Long gameTeamId, @Param("cheerCount") int cheerCount);
👍🏻 확인해씁니다

2023-11-14 12:25 UTC, Jin409 commented on src/test/java/com/sports/server/game/acceptance/GameTeamAcceptanceTest.java
> +                .isEqualTo(cheerCountBeforePost + 1);
추가했습니다!

2023-11-14 12:33 UTC, merged