Feature/#53 comment post
hufs-sports-live/server pull request #54
Opened 2023-11-15 02:49 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분
BadwordFiltering 클래스와 결합도를 낮추고 싶어서 어떻게 할까 고민 중입니다..!
BadwordFiltering 라이브러리에 코드 변경이 생기면, 저희 코드인 CommentService에도 변경이 전파되지 않도록 하고 싶은데요, 내부에서 객체를 만들어서 한번 더 감싸서 CommentService 로 전달하는 게 좋으려나요? 의견이 궁금합니다!

record 로 request dto 를 수정함에 따라 validatorMesages 를 삭제했는데요, 이 경우에는 어떻게 특정 필드에 대한 예외 처리를 할 수 있을까요? ex. request dto 에서 comment 가 Null 로 올 경우

2023-11-17 13:09 UTC, ldk980130 requested changes
질문 주신 것에 대해 코멘트 남겼습니다! 그리고 생각해볼 점도 남겨두었으니 한 번 고민해보시면 재밌을 것 같아요 ㅎㅎ

그리고 인수 테스트도 작성해주세요!

2023-11-17 13:09 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/util/BadWordFilter.java
> +}
> 라이브러리에서 제공하는 BadwordFiltering 클래스와 결합도를 낮추고 싶었습니다.
BadwordFiltering 라이브러리에 코드 변경이 생기면, 저희 코드인 CommentService에도 변경이 전파되지 않도록 하고 싶어서 자체적으로 BadWordFilter 객체 내부에 BadwordFiltering 을 선언해서 한번 더 감싸고 CommentService 에서 의존하도록 했는데요..
이상할까요? 라이브러리에 속한 객체에 대해서 이렇게 수정해본 것은 처음이라 의견이 궁금합니다.

이런 고민 너무 좋습니다! 맞아요. `BadWordFiltering`은 저희가 제어할 수 없는 외부 라이브러리입니다. 어떻게 보면 데이터베이스나 신고 검사 람다 서버처럼 인프라의 영역과 비슷하죠. (어떤 인프라 요소를 사용되도로 변경될 수도 있구요.) 저라면 이 라이브러리는 `infrastructure` 패키지에 넣을 것 같아요.

### 의존성의 방향
`BadWordFiltering`이 인프라라면 지금 구조에서 의존성의 방향에도 문제가 있어요. `application`, `infrastructure`가 있을 때 `infrastructure`는 `application`을 의존해도 되지만 반대의 의존성은 생겨서는 안됩니다.  

결합도를 낮추는 것도 중요하지만 생각해봐야 할 건 의존성의 방향입니다. 현재는 `application` -> `infra` 방향으로 의존 방향이 흐르고 있어요. 어떻게 하면 이 문제를 해결할 수 있을까요?

[인터페이스로 의존성 방향 역전하기](https://github.com/ldk980130/TIL/blob/main/design/domain-driven-design/02-architecture.md#22-%EA%B3%84%EC%B8%B5-%EA%B5%AC%EC%A1%B0-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98)

힌트
- '나쁜 말이 포함된 댓글은 달지 못한다.'는 저희 도메인의 규칙입니다. 이 요구사항 자체는 인프라적인 요소가 아니에요. 만약 외부 라이브러리나 인프라를 사용하지 않고 자바로만 이 규칙을 구현할 수 있었다면 domain 내부에 이 로직이 위치했을 것입니다.
- 저희는 왜 `repository` 인터페이스를 도메인 내부에 위치시킬까요? 데이터베이스는 인프라 아니였던가요? 도메인을 저장하고, 찾아오고 하는 일도 결국 도메인이 가져야할 명세이지만 그 구현체는?

2023-11-17 13:09 UTC, ldk980130 commented on src/test/java/com/sports/server/comment/application/CommentServiceTest.java
> +    }
좀 더 다양한 상황이 테스트되면 좋겠어요!

1. 욕이 아닌 다양한 경우가 정상적으로 저장되는지
2. 욕인 다양한 경우가 예외를 발생시키는지

Junit의 `ParameterizedTest`에 대해 알아볼까요?

2023-11-20 06:23 UTC, Jin409 commented on src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java
> +) {
해당 부분 테스트를 어떻게 진행해야 할지 모르겠네요,.,. 
인수 테스트에서 진행했더니 @Nonnull 이 컴파일 타임의 validation 이라 런타임 시에는 예외가 잡히지 않네요,, 
인수 테스트가 아닌 경우에는 CommentRequestDto 를 생성할 시에 null 을 인자로 넣고 예외가 던져지는지 확인하는 정도?! 가 있을 것 같은데 너무 간단해서 이가 적절한 테스트일지 고민이 됩니다..! 의견 있으신지 여쭤보고 싶어요!

2023-11-20 06:42 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java
> +) {
아래처럼 Map을 이용해 request body를 구성할 수도 있습니다.
``` java
        Map<String, Object> request = new HashMap<>();
        request.put("content", null);
        request.put("gameTeamId", gameTeamId);
        RestAssured.given().log().all()
                .when()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .body(request)
                .post("/comments")
                .then().log().all()
                .extract();
```

너무 간단한 테스트라는건 없는 것 같아요! 테스트를 하는 목적 중 하나가 개발자 자신이 마음의 평온(?)을 얻는 것도 있는데 확실하지 않은 동작 사항을 확인하려고 테스트를 작성하는게 나쁜건 아닌 것 같아요.

2023-11-20 06:56 UTC, Jin409 commented on src/main/java/com/sports/server/comment/util/BadWordFilter.java
> +}
반영했습니다! 한번 보시고 코멘트 부탁드립니당 ㅎㅎ

2023-11-20 06:56 UTC, Jin409 commented on src/test/java/com/sports/server/comment/application/CommentServiceTest.java
> +    }
반영했습니다! 조언 감사합니닷! :)

2023-11-20 07:12 UTC, ldk980130 approved these changes
댓글 저장 기능 수고하셨습니다! 간단한 거 조금만 몇 가지 코멘트 남겼어요. 확인하고 수정하거나 답변 달아주시고 머지하면 될 것 같습니다. 수고하셨습니다!

2023-11-20 07:12 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/application/CommentService.java
> +import com.sports.server.comment.domain.BadWordFilter;
👍 이렇게 되면 이제 나쁜말을 어떻게 필터링하는지 구현 내용이 변경되어도 CommentService는 변화가 ㅇ벗을 수 있게 되었습니다

2023-11-20 07:12 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/infra/BadWordFilterImpl.java
> +public class BadWordFilterImpl implements com.sports.server.comment.domain.BadWordFilter {
사소한 거지만 이름이 같으니 풀 패키지 이름을 가져와야 하네요. `BadWordFilter`도 일반적인 이름이긴 하지만 다른 이름으로 가져가면 어떨까요? 

나중에 잘못 임포트할 실수를 할 수도 있을 것 같아서요!

2023-11-20 07:12 UTC, ldk980130 commented on src/main/java/com/sports/server/comment/infra/BadWordFilterImpl.java
> +}
오버라이드 하는 메서드에는 `@Override` 어노테이션을 달아서 인터페이스의 메서드라는 걸 표시하면 좋을 것 같습니다

2023-11-20 07:12 UTC, ldk980130 commented on src/test/resources/comment-fixture.sql
> +       ('2023-01-04 18:15:00', 'Unbelievable goal!', false, 1);
댓글을 저장하는 테스트에 필요한 픽스처인데 이렇게 사전 데이터가 많이 필요한가요? 꼭 필요한 데이터만 넣으면 가독성도 더 좋아질 것 같습니다!

외래키를 풀고 넣은 다음 다시 외래키를 거는 이유도 필요하지 않은 데이터까지 생성하지 않기 위함이에요. 이왕 외래키를 푸는 김에 꼭 필요한 데이터만 넣으면 어떨까요?

2023-11-20 07:14 UTC, Jin409 commented on src/main/java/com/sports/server/comment/application/CommentService.java
> +import com.sports.server.comment.domain.BadWordFilter;
이번에도 재밌어씁니다 ㅎㅎ 👍🏻

2023-11-20 07:19 UTC, Jin409 commented on src/main/java/com/sports/server/comment/infra/BadWordFilterImpl.java
> +public class BadWordFilterImpl implements com.sports.server.comment.domain.BadWordFilter {
그렇네요! languageFilter 로 수정했습니닷

2023-11-20 07:26 UTC, merged