Feature/#60 games all
hufs-sports-live/server pull request #65
Opened 2023-11-22 01:57 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분

2023-11-22 07:32 UTC, ldk980130 requested changes
어쩌다보니 정말 크고 어려운 기능을 담당하게 되었네요ㅠ 그만큼 코드리뷰할 것도 많아진 것 같습니다.

### 페이징 관련 값 dto로 받기
> 페이징을 할 때 request dto 라고 이름 짓고 @ModelAttribute 로 받도록 했는데, request dto 는 아닌 것 같기도 해서 해당 부분에 대해 피드백 주시면 좋을 것 같습니다!

저도 `PageRequestDto` 같은 객체를 만들어서 사용했던 경험이 있어요! 페이징을 할 때 cursor, size, sort 등의 정보는 범용적으로 쓰이니 만들어서 사용하는거 나쁘지 않은 것 같습니다

### 페이징 테스트
> 페이징이나 쿼리스트링 관련해서 추가할 테스트가 더 보이시면 알려주세요!

몇 가지 코멘트 달아 놓은 것도 있고 테스트가 더 추가되면 좋을 것 같긴 합니다.
1. 커서 페이징 테스트 추가하기 (null일 때는 제일 최근거, 4이면 4번 경기보다 더 늦게 시작되는 경기부터 조회가 잘 되는지?)
2. 스포츠를 여러개 설정했을 때도 정확히 잘 조회가 되는지
3. 리그를 설정했을 때는 다른 리그의 경기는 보이지 않는지

제가 예전에 동적 쿼리 테스트 작성했던 예제입니다. 참고해도 좋을 것 같아요~
[예제 테스트](https://github.com/kusitms-wannafly/wannafly_be/blob/main/src/test/java/com/kusitms/wannafly/query/service/ApplicationFormQueryServiceTest.java)

2023-11-22 07:32 UTC, ldk980130 commented on src/main/java/com/sports/server/common/config/QueryDslConfig.java
> +public class QueryDslConfig {
나중에 command-query 패키지 리팩터링할 때 querydsl 관련 설정은 query 패키지 내부의 config 패키지에 두면 더 좋을 것 같네요

2023-11-22 07:32 UTC, ldk980130 commented on src/main/java/com/sports/server/game/application/GameService.java
> +                                             final List<Long> sportIds, final PageRequestDto pageRequest) {
`leagueId`, `stateValue`, `sportsId`는 검색 조건에 사용되는 친구들인데요. 만약 이 조건들이 변화하면 이 메서드 시그니쳐도 변화할 수 있겠네요. requestDto처럼 하나의 객체로 묶는건 어떨까요?

2023-11-22 07:32 UTC, ldk980130 commented on src/main/java/com/sports/server/game/application/GameService.java
> +                        game.getSport()))
이렇게 하면 게임 개수만큼 팀 조회 쿼리가 발생하는 N + 1 문제가 발생해요. 조인으로 해결할 수도 있지 않을까요? 그런데 조인을 한다고 해도 game-team 일대다 관계에서 조인과 페이징을 같이할 때 발생하는 문제점이 있어요.

페이징 일대다 조인과 관련하여 알아본 뒤 쿼리를 최적화해 보는건 어떨까요?

2023-11-22 07:32 UTC, ldk980130 commented on src/main/java/com/sports/server/game/domain/GameState.java
> +
사소한 네이밍 관련 코멘트입니다.

보통 이렇게 메서드를 통해 객체를 생성 및 반환하는 것을 정적 팩터리 메서드 패턴이라고 하는데요. 정적 팩터리 메서드 패턴에서도 네이밍 컨벤션이 있어요. 한 번 알아보고 적용해보는 건 어떨까요?
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2023-11-22 07:32 UTC, ldk980130 commented on src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
> +    }
커서의 기준이 id가 맞을까요? 정렬 기준이 경기 시작 시간이기 때문에 `id` 순서와 `startTime` 순서가 일치하지 않을 수 있어요.

정확한 페이징이 수행되려면 `cursor`의 `startime`보다 더 나중에 시작되는 경기를 찾아오는 방식으로 커서 페이징이 수행되어야할 것 같습니다.

2023-11-22 07:32 UTC, ldk980130 commented on src/main/java/com/sports/server/game/presentation/GameController.java
> +            @RequestParam(value = "sport_id", required = false) List<Long> sportIds,
얘들도 적절한 네이밍을 통해 MoedlAttribue로 받아오면 어떨까요? 아니면 이렇게 분리해 놓는게 더 좋을까요?

2023-11-22 07:32 UTC, ldk980130 commented on src/test/java/com/sports/server/game/application/GameServiceTest.java
> +    class PagingTest {
중첩 클래스를 사용해서 테스트할 때는 `@Nested` 어노테이션을 붙여야 테스트가 실행됩니다!

2023-11-22 07:32 UTC, ldk980130 commented on src/test/java/com/sports/server/game/application/GameServiceTest.java
> +
단 2개만 확인해도 문제 없는걸까요? 👀

2023-11-22 07:32 UTC, ldk980130 commented on src/test/java/com/sports/server/game/application/GameServiceTest.java
> +        }
이런 테스트는 이렇게 if문으로 검증하는 것보다 다음의 방법은 어떨가요?

1. 3개의 경기 데이터를 준비합니다.
2. 2개는 startTime이 같게 설정하고 하나는 다르게 설정합니다.

3개를 조회하게 되었을 때 startTime의 같은 2개가 id에 따라 정렬되고 startTime이 다른 하나가 또 알맞게 정렬될테니 그 3개의 전체 순서를 한 번만 확인하면 검증할 수 있지 않을까요?

2023-11-23 07:15 UTC, Jin409 commented on src/main/java/com/sports/server/game/application/GameService.java
> +                                             final List<Long> sportIds, final PageRequestDto pageRequest) {
반영했습니다!
record 로 처음에 구현했는데 쿼리스트링의 key 값과 객체의 필드명이 불일치해서 setter 로 재정의해야 하다보니 class 로 구현했습니다!

2023-11-23 07:23 UTC, Jin409 commented on src/main/java/com/sports/server/game/domain/GameState.java
> +
반영했습니다. from 으로 했는데 어떨지 모르겠네요 😓

- 하나의 매개변수를 받는다
- 매개변수를 하나 받아서 해당 타입의 인스턴스를 반환하는 형변환 메소드

를 from 으로 칭한다는 것을 보고 그렇게 명명했습니다!

2023-11-23 07:43 UTC, Jin409 commented on src/main/java/com/sports/server/game/presentation/GameController.java
> +            @RequestParam(value = "sport_id", required = false) List<Long> sportIds,
개인적으로 가독성도 좋지 않은 것 같고, 검색할 때에 필요한 조건들이 한 군데에 모여있는 것이 수정하기에도 편할 것 같아서 @ModelAttribute 를 이용해 수정했습니다!

2023-11-24 09:10 UTC, Jin409 commented on src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
> +    }
반영했습니다! 한번 확인해봐주시면 좋을 것 같습니다 👀

- startTime 이 cursor 에 해당하는 경기와 같은 경우
   - `and` cursor 에 해당하는 경기보다 아이디가 큰 경기들
- `or` startTime 이 cursor에 해당하는 경기보다 이후인 경우

를 찾아서 반환하도록 했습니다!

2023-11-24 15:50 UTC, Jin409 commented on src/main/java/com/sports/server/game/application/GameService.java
> +                        game.getSport()))
제가 해당 문제에 대해서 여러 방법을 찾아봤는데요..

### 다대일에서 발생하는 N+1 문제를 해결하기 위해서는 fetch join 을 해야 한다.
이 부분은 익히 알고 있었습니다..

### 그러나 fetch join 은 페이징이 불가능 하다.
실제로 쿼리를 확인해보니 limit 이 걸리지 않더라구요

### batch size
페이징 + N+1 문제를 해결하기 위해서는 양방향으로 연관관계를 걸고, batch size 를 이용하면 된다고 하더라구요..

```java
 @BatchSize(size = 100)
    @OneToMany(mappedBy = "game")
    private List<GameTeam> gameTeams = new ArrayList<>();
```
그래서 Game 엔티티에 위와 같이 적용하고 돌려봤더니 N+1 문제가 발생하지는 않는데, 저번 리뷰에서 화면에 맞춰서 양방향 연관관계를 맺지 말자고 했던게 생각나서 혹시 이 방법이 아닌건가?! 하는 생각이 들어서요!
다른 방법이 있다면 힌트나,, 코멘트 주실 게 있으신가요?!

2023-11-25 03:15 UTC, ldk980130 commented on src/main/java/com/sports/server/game/application/GameService.java
> +                        game.getSport()))
그러고보니 game -> gameTeam으로의 매핑이 존재하지 않네요. 말씀해주신대로 조회로직 때문에 도메인 코드가 변경되면 안되니 다른 방법을 써야겠어요. (양방향이 맺어져 있는 경우엔 페치조인과 batchsize를 조절하는 방법을 많이 쓰긴 합니다!)

일단 생각해볼 수 있는 방법은 쿼리를 2번 보내는 방법이 있네요. 
1. 게임만 조회하는 쿼리를 1번 보내고
2. 조회한 game_id 여러개를 in절에 사용해서 gameTeam들을 조회
3. 자바 코드로 묶어서 dto로 반환

2023-11-25 03:17 UTC, ldk980130 commented on src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
> +    }
로직을 눈으로 확인하는 것도 좋지만 테스트를 통해 확인하는게 더 마음 편할 것 같습니다!

예를 들어 게임들이 시작시간 순서대로 1, 2, 3, 4, 5번 게임이 있다고 하면
1. cursor가 없는 경우엔 1, 2, 3, 4, 5 순서로 조회됨
2. cursor=3인 경우엔 4, 5만 조회됨

강조했듯이 시작시간 순서 == game_id 순서는 아니기 때문에 이 점 유의해서 테스트 픽스처를 세팅한 후 테스트해보면 좋을 것 같습니다.

위와 같은 테스트가 통과된다면 정확한 로직일거에요

2023-11-26 07:26 UTC, ldk980130 approved these changes
수고하셨습니다! 👍 👍 👍

2023-11-26 07:32 UTC, merged